# Generated by Django 6.0.5 on 2026-05-09 06:44

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFloat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_float',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_missed', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_approved', 'Auto Approved'), ('manual_review', 'Manual Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('auto_approve_threshold', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=8)),
                ('admin_notes', models.TextField(blank=True)),
                ('funding_source', models.CharField(default='demo_float', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_claims',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_premium', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=8)),
                ('coverage_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('total_premiums_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('funding_source', models.CharField(default='demo_float', max_length=100)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insurance_policies',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate_monthly', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('total_repayable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('partially_repaid', 'Partially Repaid'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('repayment_schedule', models.JSONField(default=list)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(default='demo_float', max_length=100)),
                ('squad_disbursement_ref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='SavingsPot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'savings_pots',
            },
        ),
    ]
