# Generated by Django 6.0.5 on 2026-05-09 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIdentityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=10)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('savings_unlocked', models.BooleanField(default=False)),
                ('insurance_unlocked', models.BooleanField(default=False)),
                ('loan_unlocked', models.BooleanField(default=False)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'economic_identity_scores',
            },
        ),
    ]
