# Generated by Django 6.0.7 on 2026-07-09 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIdentityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=10)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('savings_unlocked', models.BooleanField(default=False)),
                ('insurance_unlocked', models.BooleanField(default=False)),
                ('loan_unlocked', models.BooleanField(default=False)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economic_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'economic_identity_scores',
            },
        ),
    ]
