# Generated by Django 6.0.5 on 2026-05-09 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('skill_required', models.CharField(choices=[('delivery', 'Delivery/Dispatch'), ('cooking', 'Cooking/Catering'), ('construction', 'Construction/Labour'), ('market', 'Market Assistant'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('teaching', 'Teaching/Tutoring'), ('other', 'Other')], max_length=30)),
                ('workers_needed', models.PositiveIntegerField(default=1)),
                ('location_area', models.CharField(max_length=200)),
                ('location_city', models.CharField(default='Lagos', max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pay_per_worker', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('source_channel', models.CharField(default='app', max_length=20)),
                ('escrow_reference', models.CharField(blank=True, max_length=200)),
                ('escrow_funded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_applications',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
