# Generated by Django 6.0.5 on 2026-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill_required',
            field=models.CharField(choices=[('delivery', 'Delivery/Dispatch'), ('cooking', 'Cooking/Catering'), ('construction', 'Construction/Labour'), ('market_assistant', 'Market Assistant'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('teaching', 'Teaching/Tutoring'), ('other', 'Other')], max_length=30),
        ),
    ]
