# Generated by Django 6.0.7 on 2026-07-09 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWithdrawalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Settled to company account via Paystack Dashboard, June 2026'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_withdrawal_log',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='platform_withdrawal_log_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('reversal', 'Reversal'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('platform_fee', 'Platform Fee'), ('withdrawal', 'Withdrawal'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('insurance_premium', 'Insurance Premium'), ('insurance_payout', 'Insurance Payout')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_tr_user_id_d7ba42_idx'), models.Index(fields=['paystack_reference'], name='payments_tr_paystac_39c3ac_idx'), models.Index(fields=['idempotency_key', 'transaction_type'], name='payments_tr_idempot_469cb1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive')],
            },
        ),
    ]
