# Generated by Django 6.0.5 on 2026-05-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('payments', '0003_reconciliation_report copy'),
    ]

    operations = [
    ]
