# Generated by Django 6.0.5 on 2026-05-13 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_0002_initial_0003_reconciliation_report copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
