# Generated by Django 6.0.5 on 2026-05-09 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('trader', 'Trader'), ('employer', 'Employer')], default='worker', max_length=20)),
                ('location_area', models.CharField(blank=True, max_length=200)),
                ('location_city', models.CharField(blank=True, default='Lagos', max_length=100)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('none', 'None')], default='none', max_length=20)),
                ('availability', models.CharField(choices=[('mornings', 'Mornings'), ('afternoons', 'Afternoons'), ('evenings', 'Evenings'), ('full_day', 'Full Day')], default='full_day', max_length=20)),
                ('trade_category', models.CharField(blank=True, max_length=100)),
                ('market_name', models.CharField(blank=True, max_length=200)),
                ('weekly_income_range', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('app', 'App'), ('ussd', 'USSD'), ('whatsapp', 'WhatsApp')], default='app', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['phone'], name='users_phone_af6883_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['location_city'], name='users_locatio_1652d1_idx')],
            },
        ),
    ]
