# Generated by Django 6.0.7 on 2026-07-09 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('pin', models.CharField(blank=True, max_length=128)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('trader', 'Trader'), ('employer', 'Employer'), ('admin', 'Admin')], default='worker', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location_area', models.CharField(blank=True, default='', max_length=255)),
                ('location_city', models.CharField(blank=True, default='Lagos', max_length=255)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, default='none', max_length=50)),
                ('availability', models.CharField(choices=[('full_day', 'Full Day'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('weekends', 'Weekends')], default='full_day', max_length=20)),
                ('trade_category', models.CharField(blank=True, default='', max_length=255)),
                ('market_name', models.CharField(blank=True, default='', max_length=255)),
                ('weekly_income_range', models.CharField(blank=True, default='', max_length=100)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(blank=True, default='app', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=8)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN Reset OTP',
                'verbose_name_plural': 'PIN Reset OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
