# Generated by Django 6.0.5 on 2026-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pinresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('trader', 'Trader'), ('employer', 'Employer'), ('admin', 'Admin')], default='worker', max_length=20),
        ),
    ]
