# Generated by Django 6.0.7 on 2026-07-09 01:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_account_number', models.CharField(blank=True, max_length=20)),
                ('paystack_account_name', models.CharField(blank=True, max_length=200)),
                ('paystack_bank_name', models.CharField(blank=True, default='Wema Bank', max_length=100)),
                ('paystack_customer_id', models.CharField(blank=True, max_length=100)),
                ('paystack_account_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('paystack_dva_id', models.CharField(blank=True, max_length=50)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bank_account_number', models.CharField(blank=True, max_length=10)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_verified', models.BooleanField(default=False)),
                ('bank_account_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_creation_status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed'), ('permanently_failed', 'Permanently Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account_number', models.CharField(max_length=10)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('rejection_reason', models.TextField(blank=True)),
                ('large_amount_override_approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('escrow_balance__gte', 0)), name='wallet_escrow_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('savings_balance__gte', 0)), name='wallet_savings_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='withdrawalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'),
        ),
    ]
