# Generated by Django 6.0.5 on 2026-05-09 06:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('squad_account_number', models.CharField(blank=True, max_length=20)),
                ('squad_account_name', models.CharField(blank=True, max_length=200)),
                ('squad_bank_name', models.CharField(blank=True, default='Squad MFB', max_length=100)),
                ('squad_customer_id', models.CharField(blank=True, max_length=100)),
                ('squad_virtual_account_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('squad_creation_status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
    ]
