# Generated by Django 6.0.5 on 2026-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_bank_account_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_account_updated_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_account_verified',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_name',
        ),
    ]
